# Tasca M3_T01

## Exercici 1

Donat el següent dataframe data = {'Col1': [50, 30, 10, 40, 20]}, ordena els valors en ordre ascendent i descendent.

In [1]:
import numpy as np


In [2]:
col_1 = [50, 30, 10, 40, 20]

In [3]:
np_col_1 = np.array(col_1)

In [4]:
np_col_1

array([50, 30, 10, 40, 20])

In [5]:
print(type(np_col_1))

<class 'numpy.ndarray'>


In [6]:
np_col_1_asc = np.sort(np_col_1)
np_col_1_asc

array([10, 20, 30, 40, 50])

Al no existir un argumento para indicarle al método .sort() que ordene los números de manera descendente busco otras formas de hacerlo

In [7]:
np_col_1_desc1 = -np.sort(-np_col_1)
np_col_1_desc1

array([50, 40, 30, 20, 10])

In [8]:
np_col_1_desc2 = np.sort(np_col_1)[::-1]
np_col_1_desc2

array([50, 40, 30, 20, 10])

In [9]:
np_col_1_desc3 = np_col_1[::1]
np_col_1_desc3

array([50, 30, 10, 40, 20])

## Exercici 2

Donat el següent dataframe data = {'Col1': [50, 30, 10, 40, 20]}, filtra els valors que siguin més grans que 30.

In [10]:
np_col_1_plus30 = np_col_1[np_col_1 > 30]
np_col_1_plus30

array([50, 40])

## Exercici 3

Donat el següent dataframe data = {'Col1': [50, 30, 10, 40, 10]}, comptabilitza els valors únics.

In [11]:
col_1_1 = [50, 30, 10, 40, 10]
np_col_1_1 = np.array(col_1_1)
np_col_1_1

array([50, 30, 10, 40, 10])

Con el método np.unique(return_counts = True) obtenemos dos arrays: uno con los números únicos y otro con su contabilidad dentro del array

In [12]:
np_col_1_1_unique = np.unique(np_col_1_1, return_counts = True)
np_col_1_1_unique

(array([10, 30, 40, 50]), array([2, 1, 1, 1]))

Para obtener solo la contabilidad utilizamos una combinación de la función len y del método np.unique: 

In [13]:
np_col_1_1_unique1 = len(np.unique(np_col_1_1))
np_col_1_1_unique1

4

## Exercici 4
Donat el següent dataframe: data = {'Grup': ['A', 'B', 'A', 'B', 'A'], 'Col1': [10, 20, 30, 40, 50]}, suma les dades que pertanyen a la mateixa columna.

In [14]:
Grup = ["A", "B", "A", "B", "A"]
Col1 = [10, 20, 30, 40, 50]
np_grup1 = np.array(Grup)
np_Col1 = np.array(Col1)
print(np_grup1)
print(np_Col1)

['A' 'B' 'A' 'B' 'A']
[10 20 30 40 50]


In [15]:
Col_A = np_Col1[np_grup1 == "A"]
Sum_Col_A = np.sum(Col_A)
Sum_Col_A

90

In [16]:
Col_B = np_Col1[np_grup1 == "B"]
Sum_Col_B = np.sum(Col_B)
Sum_Col_B

60

## Exercici 5

Donat el següent dataframe: data = {'Grup': ['A', 'B', 'A', 'B', 'A'], 'Col1': [10, 20, 30, 40, 50]}, crea una columna nova ‘Col2’ que sigui 2 si és superior al percentil 75% de la ‘Col1’, 0 si és inferior al 25% del percentil de la columna ‘Col1’ i 1 si cau entremig.



In [17]:
import pandas as pd 

In [18]:
data = {'Grup': ['A', 'B', 'A', 'B', 'A'], 'Col1': [10, 20, 30, 40, 50]}
exercici_5 = pd.DataFrame(data)
exercici_5

Grup  Col1
0    A    10
1    B    20
2    A    30
3    B    40
4    A    50

In [21]:
def agregar_col_percentil(exercici_5, columna):
    percentile_25 = np.percentile(exercici_5["Col1"],25)
    percentile_75 = np.percentile(exercici_5["Col1"],75)
    exercici_5["Col2"] = np.where(exercici_5["Col1"] > percentile_75, 2, 
                         np.where(exercici_5["Col1"] < percentile_25,0, 1))
    return exercici_5

agregar_col_percentil(exercici_5, "Col2")

Grup  Col1  Col2
0    A    10     0
1    B    20     1
2    A    30     1
3    B    40     1
4    A    50     2

## Exercici 6

Donat el següent dataframe: data = {'Grup': ['A', 'B', 'A', 'B', 'A'], 'Col1': [10, 20, 30, 40, 50]}, aplica lambda per obtenir el quadrat de la columna ‘Col1’ en una nova columna.

In [22]:
exercici_5["Col3"] = exercici_5["Col1"].apply(lambda x: x ** 2)
exercici_5

Grup  Col1  Col2  Col3
0    A    10     0   100
1    B    20     1   400
2    A    30     1   900
3    B    40     1  1600
4    A    50     2  2500