# Tasca M3 T01

## Exercici 1

Carregar “data” i "features" del conjunt de dades, i visualitza els 10 primers registres de cadascun.

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [30]:
iris = load_iris()

data = iris.data #datos de cada registre
feature = iris.feature_names # nombre de cada columna
target = iris.target # tipo de especie a la que pertenece cada registro
species = iris.target_names # nombre de cada especie

In [4]:
data_np = np.array(data)
feature_np = np.array(feature)

In [5]:
data_np[:10 :]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [6]:
feature_np # Como el array feature_np tiene solo 4 objetos, lo consultamos completo

array(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'], dtype='<U17')

## Exercici 2

Concatena “data” i “features” en un nou array. Mostra els 5 primers registres.

In [7]:
# Como el array feature.np es 1D tenemos que aplicar el método reshape(1, -1) para transformarlo 
# en un array 2D y poder realizar el concatenate. 
feature_reshape = feature_np.reshape(1, -1)
feature_reshape

array([['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
        'petal width (cm)']], dtype='<U17')

In [53]:
# Aquí ubique el array feature_reshape como el primer argumento de la función concatenate para 
# que en el array resultante apareciera como header de cada columna. 
data_feature = np.concatenate((feature_reshape, data_np))
print("Los cinco primeros registros del array resultante después de concatenar feature y data son: ")
data_feature[:5 :]

Los cinco primeros registros del array resultante después de concatenar feature y data son: 


array([['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
        'petal width (cm)'],
       ['5.1', '3.5', '1.4', '0.2'],
       ['4.9', '3.0', '1.4', '0.2'],
       ['4.7', '3.2', '1.3', '0.2'],
       ['4.6', '3.1', '1.5', '0.2']], dtype='<U32')

## Exercici 3

Calcula la mitjana i desviació estàndard de la longitud del sèpal ("sepal length (cm)") i la longitud del pètal ("petal length (cm)"). Mostra els resultats amb dos decimals.

In [57]:
# En los dos casos utilicé las funciones mean std y round de numpy 

sepal_length_mean = np.mean(data_np[: , 0])
sepal_length_std = np.std(data_np[: , 0])

print("La media de la longitud del sépalo es", np.round(sepal_length_mean, 2))
print("La desviación estándar de la longitud del sépal es", np.round(sepal_length_std, 2))

La media de la longitud del sépalo es 5.84
La desviación estándar de la longitud del sépal es 0.83


In [59]:
petal_length_mean = np.mean(data_np[: , 2])
petal_length_std = np.std(data_np[: , 2])
print("La media de la longitud del sépalo es", np.round(petal_length_mean, 2))
print("La desviación estándar de la longitud del sépal es", np.round(petal_length_std, 2))

La media de la longitud del sépalo es 3.76
La desviación estándar de la longitud del sépal es 1.76


## Exercici 4
Selecciona una mostra aleatòria de 20 registres del conjunt que has obtingut en l'exercici anterior.

In [63]:
#Como la función random.choice no puede utilizarse en un array 2D, útilizamos el la función
#shape para extraer el tamaño de la primera columna (que nos indicará el tamaño de la muestra)
#El replace=False se utiliza para no existan registros repetidos. 

random_sample = np.random.choice(data_np.shape[0], size=20, replace=False)

In [64]:
print(data_np[random_sample])

[[6.1 2.8 4.7 1.2]
 [5.7 3.8 1.7 0.3]
 [6.9 3.1 5.1 2.3]
 [5.5 2.6 4.4 1.2]
 [5.  3.5 1.3 0.3]
 [5.4 3.4 1.7 0.2]
 [5.  3.3 1.4 0.2]
 [4.9 3.6 1.4 0.1]
 [6.1 3.  4.6 1.4]
 [5.7 2.8 4.5 1.3]
 [5.4 3.9 1.3 0.4]
 [6.2 2.9 4.3 1.3]
 [7.7 2.6 6.9 2.3]
 [4.8 3.  1.4 0.1]
 [6.3 2.7 4.9 1.8]
 [5.  3.6 1.4 0.2]
 [5.1 3.8 1.5 0.3]
 [7.  3.2 4.7 1.4]
 [5.8 2.7 5.1 1.9]
 [5.4 3.9 1.7 0.4]]


## Exercici 5

Crea una matriu que mostri: 

• La mitjana de cada característica per espècie. 

• La desviació estàndard de cada característica per espècie.

In [13]:
# Creamos un DataFrame utilizando como valores los contenidos en el array data_np y como headers 
# el array feature_np
data_pd = pd.DataFrame(data=data_np, columns=feature_np)

In [86]:
data_pd.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  length_diff  
0  setosa          3.7  
1  setosa          3.5  
2  setosa          3.4  
3  setosa          3.1  
4  setosa          3.6

In [70]:
#Creamos una nueva columna "species" utilizando como datos los contenidos en el array species y
# y como criterio de ubicación el array target
data_species = data_pd['species'] = species[target]

In [72]:
#Utilizando como criterio "species" utilizo un grupby al que aplico los métodos de agregación
#"mean" y "std"
mean_species = data_pd.groupby("species").agg(["mean", "std"])
mean_species

sepal length (cm)           sepal width (cm)            \
                        mean       std             mean       std   
species                                                             
setosa                 5.006  0.352490            3.428  0.379064   
versicolor             5.936  0.516171            2.770  0.313798   
virginica              6.588  0.635880            2.974  0.322497   

           petal length (cm)           petal width (cm)           length_diff  \
                        mean       std             mean       std        mean   
species                                                                         
setosa                 1.462  0.173664            0.246  0.105386       3.544   
versicolor             4.260  0.469911            1.326  0.197753       1.676   
virginica              5.552  0.551895            2.026  0.274650       1.036   

                      
                 std  
species               
setosa      0.348852  
versicolor  0.348501  
virginica   0.319923

## Exercici 6
• Calcula la quantitat de mostres per espècie.

• Troba l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"

In [37]:
#Utilizo el método .value_counts para determinar cuántas muestras contiene cada especie

species_count = data_pd["species"].value_counts()
print("Cantidad de muestras por especie: ")
print(species_count)

Cantidad de muestras por especie: 
setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64


In [75]:
#Con un groupby en el cuál uso como criterio de agrupación "species" y como valores 
#"sepal length (cm)" aplico el método mean. Para determinar el id del valor máximo del 
#resultado de la agrupación utilizo el método .idxmax()

max_mean_sepal_lenght = data_pd.groupby("species")["sepal length (cm)"].mean().idxmax()

In [76]:
max_mean_sepal_lenght

'virginica'

## Exercici 7
• Calcula la matriu de correlació entre les variables.

• Filtra els valors majors a la mitjana de la longitud dels pètals i mostra-ho. 

• Troba la mostra amb els pètals més grans.

In [40]:
#Utilizo la función pd.corr con el argumento numeric_only=True para que solo calcule la 
#correlación de variables numéricas

print(data_pd.corr(numeric_only=True))

                   sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   

                   petal width (cm)  
sepal length (cm)          0.817941  
sepal width (cm)          -0.366126  
petal length (cm)          0.962865  
petal width (cm)           1.000000  


In [ ]:
# Los resultados los leemos como: 
# - Existe una alta correlación (0.9628) positiva entre el largo y el ancho de los pétalos, 
# lo que quiere decir que pétalos más largos serán casi siempre más anchos. 
# - Sin embargo, en el caso del ancho y el largo de los sépalos aunque la correlación positiva
# (0.8179) es alta no lo es tanto como en el caso de los pétalos. 
# -Un sépalo más largo casi siempre tendrá pétalos más largos (0.8718), pero un sépalo más  
# ancho no representa una correlación significativa con un pétalo más ancho (-0.3661)

In [84]:
petalos_mean_mas = data_pd[data_pd["petal length (cm)"] > petal_length_mean]
print(petalos_mean_mas[["petal length (cm)"]])
print("El numero de observaciones que están sobre la media del largo de los pétalos es:",
      len(petalos_mean_mas))

     petal length (cm)
50                 4.7
51                 4.5
52                 4.9
53                 4.0
54                 4.6
..                 ...
145                5.2
146                5.0
147                5.2
148                5.4
149                5.1

[93 rows x 1 columns]
El numero de observaciones que está sobre la media del largo de los pétalos es: 93


In [77]:
#Utilice otro código para comprobar el resultado
mean_petal_length = data_pd['petal length (cm)'].mean()
petalos_mayor_media = data_pd[data_pd['petal length (cm)'] > mean_petal_length]
petalos_mayor_media

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
50                 7.0               3.2                4.7               1.4   
51                 6.4               3.2                4.5               1.5   
52                 6.9               3.1                4.9               1.5   
53                 5.5               2.3                4.0               1.3   
54                 6.5               2.8                4.6               1.5   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

        species  length_diff  
50   versicolor          2.3  
51   versicolor          1.9  
52   versicolor          2.0  
53   versicolor          1.5  
54   versicolor          1.9  
..          ...          ...  
145   virginica          1.5  
146   virginica          1.3  
147   virginica          1.3  
148   virginica          0.8  
149   virginica          0.8  

[93 rows x 6 columns]

In [80]:
#Utilizo el pd.loc para seleccionar la columna "petal length (cm)" y luego de aplicar el método 
#.idxmax determinar la muestra del pétalo más grande. 

big_sample_petal = data_pd.loc[data_pd['petal length (cm)'].idxmax()]
print("La muestra del pétalo más largo es: ")
print(big_sample_petal)

La muestra del pétalo más grande es: 
sepal length (cm)          7.7
sepal width (cm)           2.6
petal length (cm)          6.9
petal width (cm)           2.3
species              virginica
length_diff                0.8
Name: 118, dtype: object


In [44]:
#Con el pd.describe() compruebo que el valor máximo del largo del pétalo es de 6.9
data_pd.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

## Exercici 8
Troba l'espècie amb la diferència més gran entre la longitud mitjana de sèpals i pètals.

In [85]:
#Creo una nueva columna que reste el largo del pétalo al largo del sépalo
data_pd["length_diff"] = data_pd["sepal length (cm)"] - data_pd["petal length (cm)"]
data_pd.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  length_diff  
0  setosa          3.7  
1  setosa          3.5  
2  setosa          3.4  
3  setosa          3.1  
4  setosa          3.6

In [89]:
#Utilizo un groupby para agrupar los valores de la nueva columna con las categorias de la 
#columna "species" y aplico el método de agregación .mean(). Si además de eso utilizo el 
#método .idxmax() solo me aparecería el nombre de la especie. En este caso prefiero también
#retornar las medias de por especie. 

groupby_diff = data_pd.groupby("species")["length_diff"].mean()
groupby_diff

species
setosa        3.544
versicolor    1.676
virginica     1.036
Name: length_diff, dtype: float64